### ISSUE TITLE
Unable to authenticate with Reddit

### ISSUE THREAD

**Issue by rickcecil** [jc9108/expanse#2]
Super excited to try this out! Thanks for making this happen! I have, though, run into a setup issue...

1. Visit https://local.domain.com/
2. Click Login with Reddit
3. Click allow from Reddit
4. Returned to https://local.domain.com/logout#_

Some notes on my configuration

- My user is in the approved list in the .env_prod file.
- I am using a subdomain on a domain that I own that is proxied through Nginx Proxy Manager, which is also listed in the config file for the callback URL and is used on Reddit as the callback URL. This domain name is not accessible to the external network.

I am seeing the following in the logs

From the database:

```
2022-09-11 20:50:17.781 UTC [69] LOG:  incomplete startup packet,
2022-09-11 20:50:17.450 UTC [1] LOG:  database system is ready to accept connections,
2022-09-11 20:50:17.446 UTC [62] LOG:  database system was shut down at 2022-09-11 20:50:17 UTC,
2022-09-11 20:50:17.440 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432",
2022-09-11 20:50:17.437 UTC [1] LOG:  listening on IPv6 address "::", port 5432,
2022-09-11 20:50:17.437 UTC [1] LOG:  starting PostgreSQL 14.5 (Debian 14.5-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit,
2022-09-11 20:50:17.437 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
```

From the app:
```
server (expanse) started on (localhost:1301)
saved user (reddituser),
checking if user (reddituser) exists,
purged user (reddituser),
denied user (reddituser),
socket (WDZoBrdZVFDhSc-1AAAL) connected,
new user (reddituser),
socket (tk5NIOso-aftuQw4AAAJ) connected,
```

I've tried to figure out where localhost:1301 is being set, but can't find it. I have found that that can cause issues if it doesn't match the domain that I a using on the network. It is updated in the .env_prod file. This may not be related to this particular issue, but thought it wroth mentioning.

Let me know what other questions you have. At the moment, this is all the info that I can find on the issue. And I fully recognize that this very well could be a pebkac errror. Any help is greatly appreciated.

**Comment by jc9108** [comment]
i am not really sure how to debug users' network errors or configs (if that is the issue here as with #1) as i am not too versed in that field unfortunately. can i ask that you try it on localhost with the default redirect uri first to confirm that it's working or not? so that we can tell if it's an issue with expanse or otherwise. though since it runs in docker and ive tested it without issue i suspect it is not

also the logs say that your user got denied. can you paste the reddit section of your env file (with sensitive info substituted)?

**Comment by jc9108** [comment]
i am not really sure how to debug users' network errors or configs (if that is the issue here as with #1) as i am not too versed in that field unfortunately. can i ask that you try it on localhost with the default redirect uri first to confirm that it's working or not? so that we can tell if it's an issue with expanse or otherwise. though since it runs in docker and ive tested it without issue i suspect it is not. after that, you are on your own as for how you host it publicly

the logs for the db are normal. the other logs say that your user got denied. can you paste the allowed and denied lists of your env file (with sensitive info substituted) here?

**Comment by rickcecil** [comment]
So, I think I figured it out. 

It was the ALLOWED_USERS list. I did not have a space between the two user IDs like so:

ALLOWED_USERS="user1,user2"

Pfft.

Excited to test it out, now!
