### ISSUE TITLE
localhost vs local IP

### ISSUE THREAD

**Issue by rastacalavera** [jc9108/expanse#20]
Hello!
I just gave this a try and I am running the project on my headless server.

When I follow your directions, it is using "localhost" so when I try to access that from the laptop and not the main server machine, it obviously doesn't work. When connecting reddit to it, I had to replace the callback url so that it used the local IP and not "localhost" like the project is setup to do.

Should I open PR with a modified readme that includes a disclaimer? Are there steps in the chain where this could be a variable that the user sets and the default is just "localhost"?

**Comment by jc9108** [comment]
ah yeah. i didnt note using the host ip in `.env_example` because you'd have to change the value at https://www.reddit.com/prefs/apps manually, every time the host ip changes. there is no way to do this programatically

so it would be easier to just host it publicly if you want to use the app from other devices. but i guess some people may have static ips in their LAN, or just dont mind dealing with this. i will include a note about using host ip in the `.env_example`. thanks for pointing it out
