### ISSUE TITLE
After some time I get a 401 error and I need to relogin and reimport everything

### ISSUE THREAD

**Issue by Z0pyrus** [jc9108/expanse#22]
When I'm not visiting my expanse instance in a while I get an 401 error and I have to login again. After logging back in all my before saved posts are gone.
These are the logs from the console:
```
getting user (myusername)
deserialize error (myusername)
Error: user (myusername) dne
    at Module.get (file:///backend/model/user.mjs:572:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///backend/controller/server.mjs:60:13
Error: user (myusername) dne
    at Module.get (file:///backend/model/user.mjs:572:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///backend/controller/server.mjs:60:13
destroyed session (myusername)
```

I haven't changed my password in the meantime or changed anything else on my reddit account. This is also not the first time that this is happening

**Comment by jc9108** [comment]
the user you logged in as was not found in the db.

the **only** times expanse ever deletes a user is 1. if you manually chose to purge it from the cog options, or 2. if that user was denied according to `.env_prod`. if neither of these apply, then i suspect your expanse db container got wiped/reset somehow, which is unrelated to expanse itself.

**Comment by Z0pyrus** [comment]
the expanse db container is running over a month without any errors

**Comment by jc9108** [comment]
ok. needing to re-login is normal if the cookie session has expired (it's set to expire if you havent visited the site in 30 consecutive days), but the user and data should still be found afterwards upon re-login, obviously. i just tested it with session expiry set to a shorter amount of time, and upon expiry and relogin everything was still there. so i was not able to reproduce this bug.

if there is further information on how to reproduce this please let me know.

**Comment by jc9108** [comment]
reopen if reproducible (with steps)

**Comment by Keagel** [comment]
The same thing just happened to me. Unfortunately I hadn't updated my container after https://github.com/jc9108/expanse/commit/9ba2e4b062bd07d24aedab7fdbe6994505794c59 so the only SQL backup I have is from 14 days ago from the built-in backup solution. I also have an external solution that I use to backup all my docker data and I just noticed that the entire database volume is empty because it's always empty on the host. I can exec into the container and see the data in `/var/lib/postgresql`, but none of those files are actually present on the host. I'm assuming I lost all the data because I rebooted the host and the data wasn't persisted.

**Comment by jc9108** [comment]
there are no operations in the (prod) app that drops the database. and users / user data is only deleted for the reasons mentioned above.

<br/>

> into the container and see the data in `/var/lib/postgresql`, but none of those files are actually present on the host

well, those files should not be present on the host at the same path (at least not from expanse); they are stored on the host as a docker named volume "db".

<br/>

did you make any changes to the env file before this happened? did you run any commands that affect docker volumes? are there any helpful logs from the db/app containers?

**Comment by jc9108** [comment]
> Unfortunately I hadn't updated my container after

ahh this gave me a clue, it may have been because `postgres:latest` changed from 14 to 15 since the release of this app. expanse was using `postgres:latest`, which was 14, and i manually set it to back to 14 with https://github.com/jc9108/expanse/commit/19900a4f7a1e13920ede8e84f8941193ee011372 21 days ago. if you didnt update expanse after that and just recreated the db container, it wouldve became postgres 15 which would be incompatible with the existing data in the db named volume, which explains why the data appeared to be lost.

so it's my bad, sorry!

if you update expanse now though (using the run script), you \*should\* have your old db back with all its data still there.

**Comment by Keagel** [comment]
> > into the container and see the data in `/var/lib/postgresql`, but none of those files are actually present on the host
> 
> well, those files should not be present on the host at the same path (at least not from expanse); they are stored on the host as a docker named volume "db".

What I meant is they're not present in the bind mount on the host. I switched from volumes to bind mounts when I set up expanse as I like to have all the docker data in one folder that I can easily backup. Here's my current config:

```
  db:
    image: docker.io/postgres:latest
    volumes:
      - /home/server/docker/appdata/expanse/db:/var/lib/postgresql
      - /home/server/docker/appdata/expanse/backups:/backups
    networks:
      - net
    env_file:
      - ./backend/.env_prod
    restart: on-failure
```

The `/home/server/docker/appdata/expanse/backups` contains the backups, it's just that the `db` folder only has the folder structure of the contents of `/var/lib/postgresql` from the container, but none of the files (and therefore data) :

### Inside container:

```
sudo docker compose exec -it db sh
# ls /var/lib/postgresql/data
base	      pg_dynshmem    pg_logical    pg_replslot	 pg_stat      pg_tblspc    pg_wal		 postgresql.conf
global	      pg_hba.conf    pg_multixact  pg_serial	 pg_stat_tmp  pg_twophase  pg_xact		 postmaster.opts
pg_commit_ts  pg_ident.conf  pg_notify	   pg_snapshots  pg_subtrans  PG_VERSION   postgresql.auto.conf  postmaster.pid
```

### On the host
```
ll /home/server/docker/appdata/expanse/db/data/
total 0
```

> > Unfortunately I hadn't updated my container after
> 
> ahh this gave me a clue, it may have been because `postgres:latest` changed from 14 to 15 since the release of this app. expanse was using `postgres:latest`, which was 14, and i manually set it to back to 14 with [19900a4](https://github.com/jc9108/expanse/commit/19900a4f7a1e13920ede8e84f8941193ee011372) 21 days ago. if you didnt update expanse after that and just recreated the db container, it wouldve became postgres 15 which would be incompatible with the existing data in the db named volume, which explains why the data appeared to be lost.
> 
> so it's my bad, sorry!
> 
> if you update expanse now though (using the run script), you *should* have your old db back with all its data still there.

I don't think it's related to my issue. I could shut down my container right now and when starting it back up I'd have lost all my data again as it's simply not persisted to the bind mounted folder. As soon as the container is destroyed the data is gone. Does `postgresql` *require* a volume instead of a bind mount?

**Comment by Keagel** [comment]
I've figured out that I have to bind the `data` directory instead of the entire `postgresql` directory for the files to be copied to the host. I'm not sure why.

```
  db:
    image: docker.io/postgres:latest
    volumes:
      - /home/server/docker/appdata/expanse/db/data:/var/lib/postgresql/data
      - /home/server/docker/appdata/expanse/backups:/backups
    networks:
      - net
    env_file:
      - ./backend/.env_prod
    restart: on-failure
```

**Comment by jc9108** [comment]
thanks for the catch, i just tested and confirmed that. i have no idea why either, it doesnt make sense that using the parent dir doesnt work but using the subdir works... anyways, if you would like to submit a PR changing the path in `compose.prod.yaml`, you would be welcome to::

https://github.com/jc9108/expanse/blob/fe96fdcea97c54b7d5ff8524fba5b467e018d178/compose.prod.yaml#L12

if not, i will do it soon
